server:
  port: 8888
spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/felipejsm/vs-config-repo
          searchPaths: product,customer,cart,payment
          username: potatoe
          password: potatoe